package com.colorclash.lan;
import android.content.res.AssetManager;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;
public class GameServer{
 private final int port;private final AssetManager assets;private final Map<String,Room>rooms=new ConcurrentHashMap<>();private volatile boolean running;private ServerSocket socket;private ExecutorService pool;
 public GameServer(int p,AssetManager a){port=p;assets=a;}
 public void start()throws IOException{if(running)return;socket=new ServerSocket();socket.setReuseAddress(true);socket.bind(new InetSocketAddress("0.0.0.0",port));pool=Executors.newCachedThreadPool();running=true;Thread t=new Thread(()->{while(running)try{Socket c=socket.accept();pool.submit(()->handle(c));}catch(IOException e){if(running)e.printStackTrace();}},"game-http");t.setDaemon(true);t.start();}
 private void handle(Socket c){try(Socket s=c){s.setSoTimeout(10000);InputStream in=s.getInputStream();OutputStream out=s.getOutputStream();ByteArrayOutputStream head=new ByteArrayOutputStream();int b,state=0;while((b=in.read())!=-1){head.write(b);if(state==0&&b=='\r')state=1;else if(state==1&&b=='\n')state=2;else if(state==2&&b=='\r')state=3;else if(state==3&&b=='\n')break;else state=(b=='\r'?1:0);if(head.size()>65536)throw new IOException("Headers too large");}String h=head.toString("ISO-8859-1");String[]lines=h.split("\r\n");if(lines.length==0)return;String[]req=lines[0].split(" ");if(req.length<2)return;String method=req[0];String target=req[1];int len=0;for(String line:lines){if(line.regionMatches(true,0,"Content-Length:",0,15))try{len=Integer.parseInt(line.substring(15).trim());}catch(Exception ignored){}}byte[]bodyBytes=new byte[Math.max(0,len)];int off=0,n;while(off<len&&(n=in.read(bodyBytes,off,len-off))>0)off+=n;String body=new String(bodyBytes,0,off,StandardCharsets.UTF_8);URI u;try{u=URI.create(target);}catch(Exception e){u=URI.create("/");}String path=u.getPath();if(path==null||path.isEmpty())path="/";Map<String,String>q=parse(u.getRawQuery()),f=parse(body);
   if(method.equals("GET")&&(path.equals("/")||path.equals("/index.html"))){sendHtml(out,readAsset("index.html"));return;}
   if(method.equals("GET")&&path.equals("/game-motion.css")){sendText(out,200,"text/css; charset=UTF-8",readAsset("game-motion.css"));return;}
   if(method.equals("GET")&&path.equals("/game-motion.js")){sendText(out,200,"application/javascript; charset=UTF-8",readAsset("game-motion.js"));return;}
   if(method.equals("GET")&&path.equals("/favicon.ico")){sendText(out,204,"text/plain",new byte[0]);return;}
   String j;if(method.equals("GET")&&path.equals("/api/status"))j=status(q);else if(method.equals("GET")&&path.equals("/api/info"))j=info();else if(method.equals("GET")&&path.equals("/api/health"))j=ok("\"service\":\"Color Clash LAN\"");else if(method.equals("POST")&&path.equals("/api/create"))j=create(f);else if(method.equals("POST")&&path.equals("/api/botmatch"))j=botMatch(f);else if(method.equals("POST")&&path.equals("/api/join"))j=join(f);else if(method.equals("POST")&&path.equals("/api/start"))j=startGame(f);else if(method.equals("POST")&&path.equals("/api/play"))j=play(f);else if(method.equals("POST")&&path.equals("/api/draw"))j=draw(f);else if(method.equals("POST")&&path.equals("/api/restart"))j=restart(f);else j=err("Not found");sendText(out,200,"application/json; charset=UTF-8",j.getBytes(StandardCharsets.UTF_8));
  }catch(Exception ignored){}}
 private byte[]readAsset(String name)throws IOException{try(InputStream in=assets.open(name);ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1)b.write(buf,0,n);return b.toByteArray();}}
 private void sendHtml(OutputStream out,byte[]data)throws IOException{String html=new String(data,StandardCharsets.UTF_8);html=html.replace("</head>","<link rel=\"stylesheet\" href=\"/game-motion.css\"></head>").replace("</body>","<script src=\"/game-motion.js\"></script></body>");sendText(out,200,"text/html; charset=UTF-8",html.getBytes(StandardCharsets.UTF_8));}
 private void sendText(OutputStream out,int status,String type,byte[]data)throws IOException{String reason=status==204?"No Content":"OK";String h="HTTP/1.0 "+status+" "+reason+"\r\nContent-Type: "+type+"\r\nContent-Length: "+data.length+"\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n";out.write(h.getBytes(StandardCharsets.US_ASCII));if(data.length>0)out.write(data);out.flush();}
 private Map<String,String>parse(String raw){Map<String,String>m=new HashMap<>();if(raw==null)return m;for(String p:raw.split("&")){int k=p.indexOf('=');try{m.put(URLDecoder.decode(k<0?p:p.substring(0,k),"UTF-8"),URLDecoder.decode(k<0?"":p.substring(k+1),"UTF-8"));}catch(Exception ignored){}}return m;}
 private String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}private String ok(String x){return "{\"ok\":true"+(x==null?"":","+x)+"}";}private String err(String e){return "{\"ok\":false,\"error\":\""+esc(e)+"\"}";}
 private String info(){String ip=lanIp();return ok("\"host\":\""+esc(ip)+"\",\"port\":"+port+",\"url\":\"http://"+esc(ip)+":"+port+"\"");}
 private String lanIp(){try{Enumeration<NetworkInterface>ifs=NetworkInterface.getNetworkInterfaces();while(ifs.hasMoreElements()){NetworkInterface nif=ifs.nextElement();if(!nif.isUp()||nif.isLoopback())continue;Enumeration<InetAddress>as=nif.getInetAddresses();while(as.hasMoreElements()){InetAddress a=as.nextElement();if(a instanceof Inet4Address&&!a.isLoopbackAddress()&&a.isSiteLocalAddress())return a.getHostAddress();}}}catch(Exception ignored){}return "127.0.0.1";}
 private String create(Map<String,String>f){String n=name(f.get("name"));if(n==null)return err("اكتب اسمك");String code;do{code=code();}while(rooms.containsKey(code));Room r=new Room(code);Player p=new Player(n,true,false);r.players.add(p);rooms.put(code,r);return ok("\"room\":\""+code+"\",\"playerId\":\""+p.id+"\"");}
 private String botMatch(Map<String,String>f){String n=name(f.get("name"));if(n==null)return err("اكتب اسمك");String code;do{code=code();}while(rooms.containsKey(code));Room r=new Room(code);Player human=new Player(n,true,false),bot=new Player("الكمبيوتر",false,true);r.players.add(human);r.players.add(bot);rooms.put(code,r);synchronized(r){setup(r);}return ok("\"room\":\""+code+"\",\"playerId\":\""+human.id+"\",\"botMode\":true");}
 private String join(Map<String,String>f){String n=name(f.get("name")),c=up(f.get("room"));if(n==null)return err("اكتب اسمك");Room r=rooms.get(c);if(r==null)return err("الغرفة غير موجودة");synchronized(r){if(r.started)return err("اللعبة بدأت");if(r.players.size()>=8)return err("الغرفة ممتلئة");Player p=new Player(n,false,false);r.players.add(p);return ok("\"room\":\""+c+"\",\"playerId\":\""+p.id+"\"");}}
 private String startGame(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(p==null||!p.host)return err("فقط المضيف يستطيع البدء");if(r.players.size()<2)return err("تحتاج لاعبين على الأقل");setup(r);return ok(null);}}
 private String restart(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(p==null||!p.host)return err("فقط المضيف");setup(r);return ok(null);}}
 private void setup(Room r){r.deck=deck();Collections.shuffle(r.deck);r.discard.clear();r.winner=null;r.direction=1;r.turn=0;r.started=true;r.nextBotAt=0;for(Player p:r.players){p.hand.clear();for(int i=0;i<7;i++)p.hand.add(take(r));}Card first=null;for(int i=0;i<r.deck.size();i++)if(r.deck.get(i).color!=null&&r.deck.get(i).value.matches("[0-9]")){first=r.deck.remove(i);break;}if(first==null)first=take(r);r.discard.add(first);r.color=first.color;scheduleBot(r);}
 private String play(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){if(!r.started)return err("اللعبة لم تبدأ");Player p=r.find(f.get("playerId"));if(p==null||r.players.get(r.turn)!=p)return err("ليس دورك");int i;try{i=Integer.parseInt(f.get("cardIndex"));}catch(Exception e){return err("بطاقة غير صحيحة");}String result=playCard(r,p,i,f.get("color"));if(result!=null)return err(result);scheduleBot(r);return ok(null);}}
 private String playCard(Room r,Player p,int i,String chosen){if(i<0||i>=p.hand.size())return "بطاقة غير صحيحة";Card c=p.hand.get(i),top=r.discard.get(r.discard.size()-1);if(!playable(c,top,r.color))return "لا يمكنك لعب هذه البطاقة";if(c.color==null){String col=chosen;if(!Arrays.asList("red","yellow","green","blue").contains(col))return "اختر لونًا";r.color=col;}else r.color=c.color;p.hand.remove(i);r.discard.add(c);if(p.hand.isEmpty()){r.winner=p.name;r.started=false;r.nextBotAt=0;return null;}effect(r,c);return null;}
 private boolean playable(Card c,Card top,String color){return c.color==null||c.color.equals(color)||c.value.equals(top.value);}
 private String draw(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(!r.started||p==null||r.players.get(r.turn)!=p)return err("ليس دورك");p.hand.add(take(r));advance(r,1);scheduleBot(r);return ok(null);}}
 private void effect(Room r,Card c){if(c.value.equals("reverse")){r.direction*=-1;advance(r,r.players.size()==2?2:1);}else if(c.value.equals("skip"))advance(r,2);else if(c.value.equals("draw2")){advance(r,1);r.players.get(r.turn).hand.add(take(r));r.players.get(r.turn).hand.add(take(r));advance(r,1);}else if(c.value.equals("wild4")){advance(r,1);for(int i=0;i<4;i++)r.players.get(r.turn).hand.add(take(r));advance(r,1);}else advance(r,1);}
 private void scheduleBot(Room r){if(r.started&&!r.players.isEmpty()&&r.players.get(r.turn).bot)r.nextBotAt=System.currentTimeMillis()+700;else r.nextBotAt=0;}
 private void maybeBot(Room r){if(!r.started||r.players.isEmpty())return;Player p=r.players.get(r.turn);if(!p.bot)return;if(r.nextBotAt==0){r.nextBotAt=System.currentTimeMillis()+700;return;}if(System.currentTimeMillis()<r.nextBotAt)return;botTurn(r,p);scheduleBot(r);}
 private void botTurn(Room r,Player p){Card top=r.discard.get(r.discard.size()-1);int best=-1,bestScore=-999;for(int i=0;i<p.hand.size();i++){Card c=p.hand.get(i);if(!playable(c,top,r.color))continue;int score=0;if(c.value.equals("wild4"))score=60;else if(c.value.equals("draw2"))score=50;else if(c.value.equals("skip"))score=40;else if(c.value.equals("reverse"))score=35;else if(c.value.equals("wild"))score=30;else score=10;score+=new Random().nextInt(8);if(score>bestScore){best=i;bestScore=score;}}if(best>=0){Card c=p.hand.get(best);String col=c.color==null?bestColor(p.hand):null;playCard(r,p,best,col);}else{p.hand.add(take(r));advance(r,1);}}
 private String bestColor(List<Card>hand){String[]cs={"red","yellow","green","blue"};int[]n={0,0,0,0};for(Card c:hand)if(c.color!=null)for(int i=0;i<4;i++)if(cs[i].equals(c.color))n[i]++;int b=0;for(int i=1;i<4;i++)if(n[i]>n[b])b=i;return cs[b];}
 private void advance(Room r,int s){for(int i=0;i<s;i++)r.turn=(r.turn+r.direction+r.players.size())%r.players.size();}private Card take(Room r){if(r.deck.isEmpty()&&r.discard.size()>1){Card t=r.discard.remove(r.discard.size()-1);r.deck.addAll(r.discard);r.discard.clear();r.discard.add(t);Collections.shuffle(r.deck);}return r.deck.isEmpty()?new Card("red","0"):r.deck.remove(r.deck.size()-1);}
 private List<Card>deck(){List<Card>d=new ArrayList<>();for(String c:new String[]{"red","yellow","green","blue"}){d.add(new Card(c,"0"));for(int n=1;n<=9;n++){d.add(new Card(c,""+n));d.add(new Card(c,""+n));}for(String v:new String[]{"skip","reverse","draw2"}){d.add(new Card(c,v));d.add(new Card(c,v));}}for(int i=0;i<4;i++){d.add(new Card(null,"wild"));d.add(new Card(null,"wild4"));}return d;}
 private String status(Map<String,String>q){Room r=rooms.get(up(q.get("room")));if(r==null)return err("الغرفة غير موجودة");synchronized(r){maybeBot(r);Player me=r.find(q.get("playerId"));if(me==null)return err("لاعب غير معروف");StringBuilder b=new StringBuilder("{\"ok\":true,\"room\":\"").append(r.code).append("\",\"started\":").append(r.started).append(",\"winner\":").append(r.winner==null?"null":"\""+esc(r.winner)+"\"").append(",\"currentColor\":\"").append(r.color).append("\",\"isHost\":").append(me.host).append(",\"players\":[");for(int i=0;i<r.players.size();i++){if(i>0)b.append(',');Player p=r.players.get(i);b.append("{\"name\":\"").append(esc(p.name)).append("\",\"count\":").append(p.hand.size()).append(",\"turn\":").append(r.started&&i==r.turn).append(",\"you\":").append(p==me).append(",\"bot\":").append(p.bot).append('}');}b.append("],\"top\":").append(r.discard.isEmpty()?"null":r.discard.get(r.discard.size()-1).json()).append(",\"hand\":[");for(int i=0;i<me.hand.size();i++){if(i>0)b.append(',');b.append(me.hand.get(i).json());}return b.append("]}").toString();}}
 private Room room(Map<String,String>f){return rooms.get(up(f.get("room")));}private String up(String s){return s==null?"":s.trim().toUpperCase(Locale.US);}private String name(String s){if(s==null||s.trim().isEmpty())return null;s=s.trim();return s.length()>20?s.substring(0,20):s;}private String code(){String a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";Random r=new Random();StringBuilder b=new StringBuilder();for(int i=0;i<5;i++)b.append(a.charAt(r.nextInt(a.length())));return b.toString();}
 static class Room{String code,color="red",winner;List<Player>players=new ArrayList<>();List<Card>deck=new ArrayList<>(),discard=new ArrayList<>();boolean started;int turn,direction=1;long nextBotAt;Room(String c){code=c;}Player find(String id){for(Player p:players)if(p.id.equals(id))return p;return null;}}
 static class Player{String id=UUID.randomUUID().toString(),name;boolean host,bot;List<Card>hand=new ArrayList<>();Player(String n,boolean h,boolean b){name=n;host=h;bot=b;}}
 static class Card{String color,value;Card(String c,String v){color=c;value=v;}String json(){return "{\"color\":"+(color==null?"null":"\""+color+"\"")+",\"value\":\""+value+"\"}";}}
}
