package com.colorclash.lan;
import android.content.res.AssetManager;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;
public class GameServer{
 private final int port;private final AssetManager assets;private final Map<String,Room>rooms=new ConcurrentHashMap<>();private volatile boolean running;private ServerSocket socket;private ExecutorService pool;
 public GameServer(int p,AssetManager a){port=p;assets=a;}
 public void start()throws IOException{if(running)return;socket=new ServerSocket();socket.setReuseAddress(true);socket.bind(new InetSocketAddress("0.0.0.0",port));pool=Executors.newCachedThreadPool();running=true;Thread t=new Thread(()->{while(running)try{Socket c=socket.accept();pool.submit(()->handle(c));}catch(IOException e){if(running)e.printStackTrace();}},"game-http");t.setDaemon(true);t.start();}
 private void handle(Socket c){try(Socket s=c){s.setSoTimeout(5000);BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream(),StandardCharsets.UTF_8));OutputStream out=s.getOutputStream();String first=r.readLine();if(first==null)return;String[]fp=first.split(" ");if(fp.length<2)return;int len=0;String line;while((line=r.readLine())!=null&&!line.isEmpty()){if(line.toLowerCase().startsWith("content-length:"))try{len=Integer.parseInt(line.substring(15).trim());}catch(Exception ignored){}}char[]ch=new char[len];int n=0,x;while(n<len&&(x=r.read(ch,n,len-n))>0)n+=x;String body=new String(ch,0,n);URI u=URI.create(fp[1]);String path=u.getPath();Map<String,String>q=parse(u.getRawQuery()),f=parse(body);String m=fp[0];if(m.equals("GET")&&path.equals("/")){respond(out,"text/html; charset=utf-8",readAsset());return;}String j;if(m.equals("GET")&&path.equals("/api/status"))j=status(q);else if(m.equals("POST")&&path.equals("/api/create"))j=create(f);else if(m.equals("POST")&&path.equals("/api/join"))j=join(f);else if(m.equals("POST")&&path.equals("/api/start"))j=startGame(f);else if(m.equals("POST")&&path.equals("/api/play"))j=play(f);else if(m.equals("POST")&&path.equals("/api/draw"))j=draw(f);else if(m.equals("POST")&&path.equals("/api/restart"))j=restart(f);else j=err("Not found");respond(out,"application/json; charset=utf-8",j.getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){}}
 private byte[]readAsset()throws IOException{try(InputStream in=assets.open("index.html");ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[]buf=new byte[8192];int n;while((n=in.read(buf))>0)b.write(buf,0,n);return b.toByteArray();}}
 private void respond(OutputStream o,String type,byte[]d)throws IOException{String h="HTTP/1.1 200 OK\r\nContent-Type: "+type+"\r\nContent-Length: "+d.length+"\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n";o.write(h.getBytes(StandardCharsets.UTF_8));o.write(d);o.flush();}
 private Map<String,String>parse(String raw){Map<String,String>m=new HashMap<>();if(raw==null)return m;for(String p:raw.split("&")){int k=p.indexOf('=');try{m.put(URLDecoder.decode(k<0?p:p.substring(0,k),"UTF-8"),URLDecoder.decode(k<0?"":p.substring(k+1),"UTF-8"));}catch(Exception ignored){}}return m;}
 private String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}private String ok(String x){return "{\"ok\":true"+(x==null?"":","+x)+"}";}private String err(String e){return "{\"ok\":false,\"error\":\""+esc(e)+"\"}";}
 private String create(Map<String,String>f){String n=name(f.get("name"));if(n==null)return err("اكتب اسمك");String code;do{code=code();}while(rooms.containsKey(code));Room r=new Room(code);Player p=new Player(n,true);r.players.add(p);rooms.put(code,r);return ok("\"room\":\""+code+"\",\"playerId\":\""+p.id+"\"");}
 private String join(Map<String,String>f){String n=name(f.get("name")),c=up(f.get("room"));if(n==null)return err("اكتب اسمك");Room r=rooms.get(c);if(r==null)return err("الغرفة غير موجودة");synchronized(r){if(r.started)return err("اللعبة بدأت");if(r.players.size()>=8)return err("الغرفة ممتلئة");Player p=new Player(n,false);r.players.add(p);return ok("\"room\":\""+c+"\",\"playerId\":\""+p.id+"\"");}}
 private String startGame(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(p==null||!p.host)return err("فقط المضيف يستطيع البدء");if(r.players.size()<2)return err("تحتاج لاعبين على الأقل");setup(r);return ok(null);}}
 private String restart(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(p==null||!p.host)return err("فقط المضيف");setup(r);return ok(null);}}
 private void setup(Room r){r.deck=deck();Collections.shuffle(r.deck);r.discard.clear();r.winner=null;r.direction=1;r.turn=0;r.started=true;for(Player p:r.players){p.hand.clear();for(int i=0;i<7;i++)p.hand.add(take(r));}Card first=null;for(int i=0;i<r.deck.size();i++)if(r.deck.get(i).color!=null&&r.deck.get(i).value.matches("[0-9]")){first=r.deck.remove(i);break;}if(first==null)first=take(r);r.discard.add(first);r.color=first.color;}
 private String play(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){if(!r.started)return err("اللعبة لم تبدأ");Player p=r.find(f.get("playerId"));if(p==null||r.players.get(r.turn)!=p)return err("ليس دورك");int i;try{i=Integer.parseInt(f.get("cardIndex"));}catch(Exception e){return err("بطاقة غير صحيحة");}if(i<0||i>=p.hand.size())return err("بطاقة غير صحيحة");Card c=p.hand.get(i),top=r.discard.get(r.discard.size()-1);if(!(c.color==null||c.color.equals(r.color)||c.value.equals(top.value)))return err("لا يمكنك لعب هذه البطاقة");if(c.color==null){String col=f.get("color");if(!Arrays.asList("red","yellow","green","blue").contains(col))return err("اختر لونًا");r.color=col;}else r.color=c.color;p.hand.remove(i);r.discard.add(c);if(p.hand.isEmpty()){r.winner=p.name;r.started=false;return ok(null);}effect(r,c);return ok(null);}}
 private String draw(Map<String,String>f){Room r=room(f);if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player p=r.find(f.get("playerId"));if(!r.started||p==null||r.players.get(r.turn)!=p)return err("ليس دورك");p.hand.add(take(r));advance(r,1);return ok(null);}}
 private void effect(Room r,Card c){if(c.value.equals("reverse")){r.direction*=-1;advance(r,r.players.size()==2?2:1);}else if(c.value.equals("skip"))advance(r,2);else if(c.value.equals("draw2")){advance(r,1);r.players.get(r.turn).hand.add(take(r));r.players.get(r.turn).hand.add(take(r));advance(r,1);}else if(c.value.equals("wild4")){advance(r,1);for(int i=0;i<4;i++)r.players.get(r.turn).hand.add(take(r));advance(r,1);}else advance(r,1);}
 private void advance(Room r,int s){for(int i=0;i<s;i++)r.turn=(r.turn+r.direction+r.players.size())%r.players.size();}private Card take(Room r){if(r.deck.isEmpty()&&r.discard.size()>1){Card t=r.discard.remove(r.discard.size()-1);r.deck.addAll(r.discard);r.discard.clear();r.discard.add(t);Collections.shuffle(r.deck);}return r.deck.isEmpty()?new Card("red","0"):r.deck.remove(r.deck.size()-1);}
 private List<Card>deck(){List<Card>d=new ArrayList<>();for(String c:new String[]{"red","yellow","green","blue"}){d.add(new Card(c,"0"));for(int n=1;n<=9;n++){d.add(new Card(c,""+n));d.add(new Card(c,""+n));}for(String v:new String[]{"skip","reverse","draw2"}){d.add(new Card(c,v));d.add(new Card(c,v));}}for(int i=0;i<4;i++){d.add(new Card(null,"wild"));d.add(new Card(null,"wild4"));}return d;}
 private String status(Map<String,String>q){Room r=rooms.get(up(q.get("room")));if(r==null)return err("الغرفة غير موجودة");synchronized(r){Player me=r.find(q.get("playerId"));if(me==null)return err("لاعب غير معروف");StringBuilder b=new StringBuilder("{\"ok\":true,\"room\":\"").append(r.code).append("\",\"started\":").append(r.started).append(",\"winner\":").append(r.winner==null?"null":"\""+esc(r.winner)+"\"").append(",\"currentColor\":\"").append(r.color).append("\",\"isHost\":").append(me.host).append(",\"players\":[");for(int i=0;i<r.players.size();i++){if(i>0)b.append(',');Player p=r.players.get(i);b.append("{\"name\":\"").append(esc(p.name)).append("\",\"count\":").append(p.hand.size()).append(",\"turn\":").append(r.started&&i==r.turn).append(",\"you\":").append(p==me).append('}');}b.append("],\"top\":").append(r.discard.isEmpty()?"null":r.discard.get(r.discard.size()-1).json()).append(",\"hand\":[");for(int i=0;i<me.hand.size();i++){if(i>0)b.append(',');b.append(me.hand.get(i).json());}return b.append("]}").toString();}}
 private Room room(Map<String,String>f){return rooms.get(up(f.get("room")));}private String up(String s){return s==null?"":s.trim().toUpperCase(Locale.US);}private String name(String s){if(s==null||s.trim().isEmpty())return null;s=s.trim();return s.length()>20?s.substring(0,20):s;}private String code(){String a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";Random r=new Random();StringBuilder b=new StringBuilder();for(int i=0;i<5;i++)b.append(a.charAt(r.nextInt(a.length())));return b.toString();}
 static class Room{String code,color="red",winner;List<Player>players=new ArrayList<>();List<Card>deck=new ArrayList<>(),discard=new ArrayList<>();boolean started;int turn,direction=1;Room(String c){code=c;}Player find(String id){for(Player p:players)if(p.id.equals(id))return p;return null;}}
 static class Player{String id=UUID.randomUUID().toString(),name;boolean host;List<Card>hand=new ArrayList<>();Player(String n,boolean h){name=n;host=h;}}
 static class Card{String color,value;Card(String c,String v){color=c;value=v;}String json(){return "{\"color\":"+(color==null?"null":"\""+color+"\"")+",\"value\":\""+value+"\"}";}}
}
